// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYn7ORu_u5oXl9-NVazEjSU3UigLmyFI',
    appId: '1:696571918517:web:0ad885c60fa8950a50a6fc',
    messagingSenderId: '696571918517',
    projectId: 'healthconnect-5fe22',
    authDomain: 'healthconnect-5fe22.firebaseapp.com',
    storageBucket: 'healthconnect-5fe22.appspot.com',
    measurementId: 'G-JTLL4K88WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9HkDMdw2kmqXecmbNOmwAeT9Rxqn8tQ',
    appId: '1:696571918517:android:36e0ef5e0ce3693550a6fc',
    messagingSenderId: '696571918517',
    projectId: 'healthconnect-5fe22',
    storageBucket: 'healthconnect-5fe22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3iesTXlBpjP3LgMWxSH8snZ-hF6fPQc',
    appId: '1:696571918517:ios:24376abf91b6116350a6fc',
    messagingSenderId: '696571918517',
    projectId: 'healthconnect-5fe22',
    storageBucket: 'healthconnect-5fe22.appspot.com',
    iosClientId: '696571918517-pfhqs7ntn4aht38g8r2casjkjb19t8ub.apps.googleusercontent.com',
    iosBundleId: 'com.jitendrad8696.healthConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3iesTXlBpjP3LgMWxSH8snZ-hF6fPQc',
    appId: '1:696571918517:ios:8a0c580ad2bfe41150a6fc',
    messagingSenderId: '696571918517',
    projectId: 'healthconnect-5fe22',
    storageBucket: 'healthconnect-5fe22.appspot.com',
    iosClientId: '696571918517-bnofs62kvec4cpm2l89doit2bnlf40er.apps.googleusercontent.com',
    iosBundleId: 'com.jitendrad8696.healthConnect.RunnerTests',
  );
}
